[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "greenfunction"
version = "0.1.0"
description = "Numerical approximation of Green functions."
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "numpy",
    "matplotlib",
]

[project.scripts]
greenfunction = "greenfunction.main:main"